name: Backend-Deploy

on:
  workflow_run:
    workflows: ["Backend-Build and Test"]  
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built Docker image
        uses: actions/download-artifact@v4
        with:
          name: backend-image
          path: backend

      - name: Load Docker image
        run: docker load -i task-scheduler-backend.tar

      - name: Stop existing container
        run: |
          CONTAINER_ID=$(docker ps -q --filter "name=task-scheduler-backend")
          if [ ! -z "$CONTAINER_ID" ]; then
            echo "Stopping existing container..."
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          else
            echo "No existing container found."
          fi

      - name: Deploy new container
        run: |
          docker run -d \
            --name task-scheduler-backend \
            -p 2108:2108 \
            --env-file .env \
            task-scheduler-backend:latest

      - name: Verify deployment
        run: |
          echo "Waiting for container to start..."
          sleep 5
          curl -f http://localhost:2108/test || (echo "App not responding!" && exit 1)

      - name: Cleanup old Docker images
        run: docker image prune -f
